# Page settings

baseURL = "https://resume.tauke.net/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-189272568-2"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Joe Tauke"
        tagline = "IT Supervisor"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Des Moines, IA"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "515-599-1625"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "jtauke@gmail.com"
      #  [[params.contact.list]]
      #  icon = "fas fa-globe"
      #  url = "#"
      #  text = "resume.tauke.net"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Microsoft Azure"
        [[params.skills.list.items]]
        details = "VMware vSphere"
        [[params.skills.list.items]]
        details = "Amazon Web Services"
        [[params.skills.list.items]]
        details = "Microsft 365 Administration"
        [[params.skills.list.items]]
        details = "Powershell"
        [[params.skills.list.items]]
        details = "Ansible"
        [[params.skills.list.items]]
        details = "Terraform"
        [[params.skills.list.items]]
        details = "Active Directory"
        [[params.skills.list.items]]
        details = "Windows Server"
        [[params.skills.list.items]]
        details = "FSLogix Profile Management"
        [[params.skills.list.items]]
        details = "SAN Management"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"
        [[params.skills.list.items]]
        details = "Desire to learn"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BS Management Information Systems"
        university = "Iowa State University"
        dates = "2008 - 2012"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Microsoft Certified: Azure Solutions Architect Expert"
        body = "Microsoft"
        date = "2021"
        [[params.awards.list]]
        name = "Microsoft Certified: Azure Administrator Associate"
        body = "Microsoft"
        date = "2019"
        [[params.awards.list]]
        name = "AWS Solutions Architect Associate"
        body = "Amazon"
        date = "2018"
        [[params.awards.list]]
        name = "Specialist – Implementation Engineer, SC Series"
        body = "Dell Technologies"
        date = "2019"
        [[params.awards.list]]
        name = "VMware Certified Professional 6.5 – Data Center Virtualization"
        body = "VMware"
        date = "2017"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Baking"
        [[params.interests.list]]
        name = "Homelab"
        [[params.interests.list]]
        name = "Technology"
        [[params.interests.list]]
        name = "Gaming"








    [params.summary]
        enable = true
        text = "Highly skilled IT consultant with 9 years of technical experience, 4 of which include supervisory duties, and a drive to never stop learning. Seeking to leverage cloud technologies and automation to propel organizations to the next level. Bachelor's degree in Management Information Systems."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Supervisor/Systems Engineer"
        dates = "2017 - Present"
        company = "Aureon"
        details = "Responsible for supervising three consultants, along with the items that entails.  Acted as a mentor for the team, approved time sheets and expenses, annual reviews, assisted with goal setting.  In addition to supervisory duties I maintained a project workload of server/san installs and any associated migrations.  Also acted as an L3 escalation point within the wider team."


        [[params.experience.list]]
        title = "Technical Consultant II"
        dates = "2016 - 2017"
        company = "Aureon"
        details = "Provided on-site technical support to assigned clients, while also completing customer project within time/budget constraints.  Worked heavily on SAN implementations (and quickly achieved a need certification).  Acted as Technical Account Manager for four customers, providing them with a technical point of contact for planning and service related items."
      #  [[params.experience.list.items]]
      #  details = "Lorem ipsum dolor sit amet, consectetuer."
      #  [[params.experience.list.items]]
      # details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Technical Consultant I"
        dates = "2015 - 2016"
        company = "Aureon"
        details = "Primarily provide on-site support to assigned customer base w/ rotating monthly preventive maintenance visits.  Assisted with customer projects when possible.  When not on-site, was remote escalation point for our help desk."










    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Kubernetes Home Lab"
        meta = "Home"
        tagline = "Created a 5 node k3s cluster using the raspberry pi 3b+ platform in an effort to learn more about the advantages of containerization and container orchestration"


        [[params.projects.list]]
        title = "Ansible"
        meta = "Open Source"
        tagline = "While looking to further leverage Ansible in orchestrating windows server deployment, found that the win_domain module lacked a needed functionality.  Was able to modify the code and submit a pull request that was merged into the main Ansible codebase."





    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/jtauke"
        title = "jtauke"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/JoeTauke"
        title = "JoeTauke"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/JoeTauke"
        title = "@JoeTauke"





